pollster/pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

pollster/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.poll, name='poll'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

pollster/pollster/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pages.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

pollster/pages/models.py
from django.db import models

# Create your models here.

pollster/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

pollster/pages/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'pages/index.html')

pollster/polls/views.py
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
# Create your views here.
from .models import Question, Choice

# Get questions and display them
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

# Show specific question and choices
def poll(request, question_id):
    print('poll')
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/poll.html', { 'question': question })

# Get question and display results
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', { 'question': question })

# Vote for a question choice
def vote(request, question_id):
    print('vote')
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'polls/poll.html', {
            'question': question,
            'error_message': 'You didn\'t select a choice',
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a 
        # user hits the Back button
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

pollster/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Fira+Code:400,700&display=swap"
      rel="stylesheet"
    />
    <title>Pollster {% block title %}{% endblock %}</title>
    <style>
      body {
        font-family: 'Fira Code', monospace;
        font-weight: 700 !important;
      }
    </style>
  </head>
  <body>
    {% include 'partials/_navbar.html' %}
    <div class="container">
      <div class="row">
        <div class="col-md-6 m-auto">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

pollster/templates/pages/index.html
{% extends 'base.html' %} {% block content %}

<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Welcome to Pollster
      </h1>
      <h2 class="subtitle">
        This is an example Django polling app
      </h2>
      <a href="{% url 'polls:index' %}" class="button is-success"
        >View Available Polls</a
      >
    </div>
  </div>
</section>

{% endblock%}

pollster/templates/partials/_navbar.html
<nav class="navbar is-success" role="navigation" aria-label="main navigation" style="margin-bottom:2em">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      Pollster
    </a>
  </div>
</nav>

pollster/templates/polls/index.html
{% extends 'base.html'%} {% block content %}
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Questions
      </h1>
    </div>
  </div>
</section>
{% if latest_question_list%} {% for question in latest_question_list %}
<div style="padding: 0 1.5rem;">
  <div class="card" style="margin-bottom:2em">
    <div class="card-content">
      <div class="subtitle">
        {{ question.question_text }}
      </div>
    </div>
    <div class="card-footer">
      <a href="{% url 'polls:poll' question.id %}" class="card-footer-item"
        >Vote Now</a
      >
      <a href="{% url 'polls:results' question.id %}" class="card-footer-item"
        >Results</a
      >
    </div>
  </div>
</div>

{% endfor %} {% else %}
<p>No polls available</p>
{% endif%} {% endblock %}

pollster/templates/polls/poll.html
{% extends 'base.html'%} {% block content %}
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        {{ question.question_text }}
      </h1>
    </div>
  </div>
</section>

{% if error_message %}

<div class="notification is-danger">
  {{ error_message }}
</div>

{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post" style="padding: 0 1.5rem;">
  {% csrf_token %} {% for choice in question.choice_set.all %}
  <div class="field">
    <div class="control">
      <input
        type="radio"
        name="choice"
        id="choice{{ forloop.counter }}"
        value="{{ choice.id }}"
      />
      <label class="radio" for="choice{{ forloop.counter }}"
        >{{ choice.choice_text }}</label
      >
    </div>
  </div>
  {% endfor %}

  <div class="field"></div>

  <div class="field is-grouped">
    <div class="control">
      <button class="button is-success"type="submit">Vote</button>
    </div>
    <p class="control">
      <a href="{% url 'polls:index' %}" class="button">Back</a>
    </p>
  </div>
</form>
{% endblock %}

pollster/templates/polls/results.html
{% extends 'base.html'%} {% block content %}

<article class="panel is-info">
  <p class="panel-heading">
    {{ question.question_text }}
  </p>
  {% for choice in question.choice_set.all %}
  <a class="panel-block is-active">
    <div
      style="display: flex; justify-content: space-between; width: 100%; align-items: center"
    >
      <p class="is-5">{{ choice.choice_text }}</p>
      <span class="tag is-info"
        >{{ choice.votes }} vote{{ choice.votes | pluralize }}</span
      >
    </div>
  </a>
  {% endfor %}
</article>

<div class="field is-grouped">
  <p class="control">
    <a href="{% url 'polls:poll' question.id %}" class="button is-success">Answer</a>
  </p>
  <p class="control">
    <a href="{% url 'polls:index' %}" class="button">
      Back
    </a>
  </p>
</div>

{% endblock %}